import type { Metadata } from 'next';
import { Geist_Mono, Tilt_Warp } from 'next/font/google';
import '@/globals.css';
import { ClientProviders } from './ClientProviders';
import { SessionProvider } from 'next-auth/react';

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const tiltWarp = Tilt_Warp({
  variable: '--font-tilt-warp',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${tiltWarp.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          <ClientProviders>{children}</ClientProviders>
        </SessionProvider>
      </body>
    </html>
  );
}
